/** Pure formatter for a VCDS-style Auto-Scan text report — the classic forum-pasteable block every
 *  VW forum reads on sight: a chassis/profile header, then per module the address + name, part
 *  number / component / software, coding (when known), and each fault as its VAG 5-digit number +
 *  SAE code + text + status flags. No I/O; kept separate from the React layer so it is unit-tested
 *  against a fixture and reused by the share action. See docs/features/module-scan.md. */

import { decodeDtcStatusByte } from '@/shared/obd-core';
import type {
  SavedScan,
  SavedScanModule,
  SavedScanDtc,
  SavedScanTp20Module,
} from '../model/scanHistoryStore';

const RULE = '-'.repeat(66);

function pad2(ts: number): string {
  const d = new Date(ts);
  const p = (n: number) => n.toString().padStart(2, '0');
  return `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())} ${p(d.getHours())}:${p(d.getMinutes())}`;
}

/** Human status flags for a fault, in the order VCDS-style tools list them; 'stored' when none set. */
export function statusFlagText(status: number): string {
  const f = decodeDtcStatusByte(status);
  const flags = [
    f.confirmed ? 'confirmed' : null,
    f.pending ? 'pending' : null,
    f.testFailed ? 'failing now' : null,
    f.testFailedThisCycle ? 'failed this cycle' : null,
    f.warningIndicator ? 'warning lamp' : null,
  ].filter(Boolean);
  return flags.length ? flags.join(', ') : 'stored';
}

function stateSummary(m: SavedScanModule): string {
  switch (m.state) {
    case 'silent':
      return 'No response (module absent, asleep, or a different address on this car).';
    case 'skipped':
      return m.reason ?? 'Skipped (different transport).';
    case 'error':
      return `Scan error: ${m.reason ?? 'unknown'}`;
    default:
      return m.dtcs.length
        ? `${m.dtcs.length} Fault${m.dtcs.length > 1 ? 's' : ''} Found:`
        : 'No fault code found.';
  }
}

function faultLine(d: SavedScanDtc): string[] {
  const vag = d.vagCode ? `${d.vagCode} - ` : '';
  return [`   ${vag}${d.display} - ${d.description}`, `      Status: ${statusFlagText(d.status)}`];
}

function moduleBlock(m: SavedScanModule): string[] {
  const lines: string[] = [];
  lines.push(`Address ${m.address}: ${m.name}`);
  if (m.partNumber) lines.push(`   Part No: ${m.partNumber}`);
  if (m.systemName) lines.push(`   Component: ${m.systemName}`);
  if (m.softwareVersion) lines.push(`   Software: ${m.softwareVersion}`);
  if (m.hardwareNumber) lines.push(`   Hardware: ${m.hardwareNumber}`);
  if (m.coding) lines.push(`   Coding: ${m.coding}`);
  if (m.experimental) lines.push('   (Addressing experimental / unverified — confirm on the car.)');
  lines.push(`   ${stateSummary(m)}`);
  if (m.state === 'ok') for (const d of m.dtcs) lines.push(...faultLine(d));
  return lines;
}

function tp20Block(m: SavedScanTp20Module): string[] {
  const lines: string[] = [];
  const addr = m.address.toString(16).padStart(2, '0').toUpperCase();
  lines.push(`Address ${addr}: ${m.name} (TP2.0)`);
  if (m.ident) lines.push(`   Component: ${m.ident}`);
  if (m.dtcs && m.dtcs.length) {
    lines.push(`   ${m.dtcs.length} Fault${m.dtcs.length > 1 ? 's' : ''} Found:`);
    for (const d of m.dtcs)
      lines.push(`   ${d.vag} - Status 0x${d.status.toString(16).padStart(2, '0').toUpperCase()}`);
  } else if (m.dtcs) {
    lines.push('   No fault code found.');
  } else {
    lines.push(`   ${m.state}`);
  }
  return lines;
}

/** Render a SavedScan as the forum-pasteable Auto-Scan block. */
export function formatAutoScanReport(scan: SavedScan): string {
  const scanned = scan.modules.filter((m) => m.state === 'ok');
  const withFaults = scanned.filter((m) => m.dtcs.length > 0);
  const totalFaults = scanned.reduce((n, m) => n + m.dtcs.length, 0);

  const lines: string[] = [];
  lines.push(RULE);
  lines.push('VCDS-style Auto-Scan — Bolid Tester');
  lines.push(`Vehicle: ${scan.vehicle.label}`);
  lines.push(`VIN: ${scan.vehicle.vin ?? 'not available'}`);
  lines.push(`Protocol: ${scan.protocol}`);
  lines.push(`Date: ${pad2(scan.ts)}`);
  lines.push(
    `Modules: ${scan.modules.length} declared, ${scanned.length} answered, ` +
      `${withFaults.length} with faults, ${totalFaults} fault${totalFaults === 1 ? '' : 's'} total`,
  );
  lines.push(RULE);

  for (const m of scan.modules) {
    lines.push('');
    lines.push(...moduleBlock(m));
  }

  if (scan.tp20 && scan.tp20.modules.length) {
    lines.push('');
    lines.push('-- Pre-UDS modules (TP2.0) --');
    for (const m of scan.tp20.modules) {
      lines.push('');
      lines.push(...tp20Block(m));
    }
  }

  lines.push('');
  lines.push(RULE);
  lines.push('End of report — generated by Bolid Tester (experimental; addresses per-car).');
  return lines.join('\n');
}
