import { formatAutoScanReport, statusFlagText } from './scanReport';
import type { SavedScan } from '../model/scanHistoryStore';

const fixture: SavedScan = {
  id: 'scan-1',
  ts: Date.UTC(2026, 6, 14, 9, 30), // 2026-07-14
  vehicle: { id: 'golf-plus-2009-20tdi', label: 'VW Golf Plus 2009 2.0 TDI 81 kW (2009)', vin: 'WVWZZZ1KZ9W903398' },
  protocol: 'ISO 15765-4 CAN (11-bit, 500 kbps)',
  modules: [
    {
      address: '01',
      name: 'Engine (EDC17)',
      state: 'ok',
      partNumber: '03L906022LM',
      softwareVersion: '4023',
      systemName: 'R4 2,0L EDC G000AG',
      experimental: false,
      dtcs: [
        { sae: 'P2183', display: 'P2183 00', vagCode: '08579', description: 'Engine coolant temperature sensor 2', status: 0x09 },
        { sae: 'P0121', display: 'P0121 00', vagCode: '00289', description: 'Throttle position sensor', status: 0x04 },
      ],
    },
    {
      address: '03',
      name: 'ABS/ESP (MK60)',
      state: 'ok',
      partNumber: '1K0907379AC',
      systemName: 'ESP FRONT MK60',
      experimental: true,
      dtcs: [{ sae: 'C0130', display: 'C0130 00', vagCode: '', description: 'ABS hydraulic pump', status: 0x88 }],
    },
    { address: '17', name: 'Instrument cluster', state: 'ok', partNumber: '5M0920861B', systemName: 'KOMBIINSTRUMENT', experimental: true, dtcs: [] },
    { address: '15', name: 'Airbag', state: 'silent', experimental: true, dtcs: [] },
  ],
  tp20: {
    installed: [0x19, 0x46],
    modules: [
      { address: 0x46, name: 'Central conv. (comfort)', state: 'ok', ident: '1K0959433 Komfortgeraet', dtcs: [{ vag: '00928', status: 0x22 }] },
    ],
  },
};

describe('statusFlagText', () => {
  it('names the set ISO 14229 flags, or "stored" when none', () => {
    expect(statusFlagText(0x09)).toBe('confirmed, failing now'); // confirmed(0x08) + testFailed(0x01)
    expect(statusFlagText(0x88)).toBe('confirmed, warning lamp');
    expect(statusFlagText(0x00)).toBe('stored');
  });
});

describe('formatAutoScanReport', () => {
  const report = formatAutoScanReport(fixture);

  it('renders the chassis / profile header with VIN, protocol and date', () => {
    expect(report).toContain('VCDS-style Auto-Scan — Bolid Tester');
    expect(report).toContain('Vehicle: VW Golf Plus 2009 2.0 TDI 81 kW (2009)');
    expect(report).toContain('VIN: WVWZZZ1KZ9W903398');
    expect(report).toContain('Protocol: ISO 15765-4 CAN (11-bit, 500 kbps)');
    expect(report).toContain('Date: 2026-07-14');
  });

  it('summarizes module + fault counts', () => {
    expect(report).toContain('4 declared, 3 answered, 2 with faults, 3 faults total');
  });

  it('renders each module with address, name, part number and component', () => {
    expect(report).toContain('Address 01: Engine (EDC17)');
    expect(report).toContain('   Part No: 03L906022LM');
    expect(report).toContain('   Component: R4 2,0L EDC G000AG');
    expect(report).toContain('   Software: 4023');
  });

  it('renders faults as VAG number + SAE code + text + status flags', () => {
    expect(report).toContain('   08579 - P2183 00 - Engine coolant temperature sensor 2');
    expect(report).toContain('      Status: confirmed, failing now');
    // C0130 has no VAG number (non-P code) — it still shows the SAE code + text.
    expect(report).toContain('   C0130 00 - ABS hydraulic pump');
  });

  it('shows clean and silent modules honestly', () => {
    expect(report).toContain('Address 17: Instrument cluster');
    expect(report).toContain('   No fault code found.');
    expect(report).toContain('Address 15: Airbag');
    expect(report).toContain('No response');
  });

  it('appends the TP2.0 section', () => {
    expect(report).toContain('-- Pre-UDS modules (TP2.0) --');
    expect(report).toContain('Address 46: Central conv. (comfort) (TP2.0)');
    expect(report).toContain('   00928 - Status 0x22');
  });

  it('marks experimental addressing and ends with the generated-by footer', () => {
    expect(report).toContain('(Addressing experimental / unverified — confirm on the car.)');
    expect(report.trimEnd().endsWith('generated by Bolid Tester (experimental; addresses per-car).')).toBe(true);
  });
});
